spring.application.name=cachingApp

spring.datasource.url=jdbc:mysql://localhost:3307/Dev
spring.datasource.username=root
spring.datasource.password=Sujit@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configurations for localhost
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

#redis configurations for Virtual DB (AWS) , info found in redis website at same db
spring.data.redis.host=water-retrovivid-irreplaceable-33138.db.redis.io
spring.data.redis.port=19212
spring.data.redis.password=fDFtosyHs8jyTTBfW18IE5KfdClZAejg
#spring.data.redis.ssl.enabled=false